#!/usr/bin/env python3
"""
retrofit_to_moodle.py — Convert older standalone lesson HTML files into
the Moodle-ready body-fragment format without re-running the AI pipeline.

Use this when:
  - A module was generated by an older version of module_pipeline.py
    (pre `.ims-lesson` scoping / pre-SVG-color-inlining).
  - You want to preserve the existing lesson text verbatim and only
    update the wrapper / styling / CSS-var handling.

The script does NOT re-call any LLM. It is pure HTML rewriting:
  1. Extracts the body of each `lessons/NN_<slug>.html`.
  2. Strips the inline <style> block (replaced by the design system CSS).
  3. Substitutes every `var(--xxx)` inside <svg> blocks with literal hex.
  4. Wraps the body in `<div class="ims-lesson">`.
  5. Writes a `lessons/NN_<slug>_moodle.html` body fragment next to the
     original standalone file.
  6. Also retrofits `00_module_overview.html` if present.

Idempotent: re-running overwrites the `_moodle.html` files in place. The
standalone `NN_<slug>.html` files are left untouched.

Usage:
    python pipeline/retrofit_to_moodle.py --module courses/aviation-weather/module-1
"""

import argparse
import re
import sys
from pathlib import Path

# Import the CSS-var scrubber and design system loader from the main pipeline
# so the retrofit and the pipeline stay in lockstep.
HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))

# These are pure-Python helpers without API dependencies, but importing
# module_pipeline pulls in `anthropic`. We re-implement the minimal bits we
# need locally to keep retrofit usable without API credentials.

CSS_VAR_HEX_FALLBACKS = {
    "--bg":            "#FFFFFF",
    "--surface":       "#F6F5F0",
    "--border":        "#E2DFD6",
    "--text":          "#1A1917",
    "--muted":         "#6B6A65",
    "--accent":        "#185FA5",
    "--accent-light":  "#E6F1FB",
    "--note-bg":       "#E1F5EE",
    "--note-border":   "#0F6E56",
    "--warn-bg":       "#FAEEDA",
    "--warn-border":   "#BA7517",
    "--key-bg":        "#EEEDFE",
    "--key-border":    "#534AB7",
    "--danger-bg":     "#FCEBEB",
    "--danger-border": "#A32D2D",
}

_VAR_RE  = re.compile(r"var\(\s*(--[A-Za-z0-9_-]+)\s*(?:,[^)]*)?\)")
_SVG_RE  = re.compile(r"<svg\b.*?</svg>", re.DOTALL | re.IGNORECASE)
_BODY_RE = re.compile(r"<body[^>]*>(.*?)</body>", re.DOTALL | re.IGNORECASE)
_H1_RE   = re.compile(r"<h1[^>]*>(.*?)</h1>", re.DOTALL | re.IGNORECASE)


def inline_css_vars_in_svgs(html: str) -> str:
    def scrub(match: re.Match) -> str:
        block = match.group(0)
        def replace_var(v: re.Match) -> str:
            return CSS_VAR_HEX_FALLBACKS.get(v.group(1), v.group(0))
        return _VAR_RE.sub(replace_var, block)
    return _SVG_RE.sub(scrub, html)


def load_design_css() -> str:
    css_file = HERE.parent / "config" / "design_system.css"
    if not css_file.is_file():
        raise SystemExit(f"design_system.css not found at {css_file}")
    return css_file.read_text(encoding="utf-8")


def extract_body(html: str) -> str:
    match = _BODY_RE.search(html)
    if match:
        return match.group(1).strip()
    # Some older outputs were already body-only; assume the whole input is body.
    return html.strip()


def strip_existing_h1(body: str) -> tuple[str, str | None]:
    """Pull the first <h1>...</h1> out of body so we can re-emit it inside
    the wrapper without duplicating it."""
    match = _H1_RE.search(body)
    if not match:
        return body, None
    title = re.sub(r"<[^>]+>", "", match.group(1)).strip()
    body = body[:match.start()] + body[match.end():]
    return body.strip(), title


def build_fragment(title: str, breadcrumb: str, body: str, css: str) -> str:
    body = inline_css_vars_in_svgs(body)
    return (
        f"<style>\n{css}\n</style>\n"
        f'<div class="ims-lesson">\n'
        f'<p class="breadcrumb">{breadcrumb}</p>\n'
        f"<h1>{title}</h1>\n"
        f"{body}\n"
        f"</div>"
    )


def retrofit_file(html_file: Path, breadcrumb: str, css: str,
                  out_file: Path) -> None:
    text = html_file.read_text(encoding="utf-8")
    body = extract_body(text)
    body, title = strip_existing_h1(body)
    if not title:
        # Fall back to a title from the filename slug.
        title = html_file.stem.replace("_", " ").title()
    fragment = build_fragment(title, breadcrumb, body, css)
    out_file.write_text(fragment, encoding="utf-8")


def run(module_dir: Path, module_number: int) -> None:
    css = load_design_css()
    lessons_dir = module_dir / "lessons"
    if not lessons_dir.is_dir():
        raise SystemExit(f"No lessons/ folder under {module_dir}")

    lesson_files = sorted(f for f in lessons_dir.glob("*.html")
                          if not f.name.endswith("_moodle.html"))
    if not lesson_files:
        print(f"No lesson HTML files in {lessons_dir}")
        return

    for i, lf in enumerate(lesson_files, 1):
        out = lf.with_name(lf.stem + "_moodle.html")
        retrofit_file(lf, f"Module {module_number} / Lesson {i}", css, out)
        print(f"  retrofitted {lf.name} -> {out.name}")

    overview = module_dir / "00_module_overview.html"
    if overview.is_file():
        out = module_dir / "00_module_overview_moodle.html"
        retrofit_file(overview, f"Module {module_number} overview", css, out)
        print(f"  retrofitted {overview.name} -> {out.name}")


def main() -> None:
    p = argparse.ArgumentParser(description=__doc__,
                                formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--module", required=True,
                   help="Path to a generated module folder.")
    p.add_argument("--module-number", type=int, default=1,
                   help="Module number (used for breadcrumbs). Default 1.")
    args = p.parse_args()
    run(Path(args.module), args.module_number)


if __name__ == "__main__":
    main()
